<script setup>
import { onMounted,ref } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import {api} from '../api'; import ModalForm from '../components/ModalForm.vue'; import StatusBadge from '../components/StatusBadge.vue'
const route=useRoute(),router=useRouter(),client=ref({}),projects=ref([]),modal=ref(false),editing=ref(false),error=ref(''),form=ref({title:'',description:'',status:'active'})
async function load(){try{[client.value,projects.value]=await Promise.all([api('/clients/'+route.params.id),api('/projects?clientId='+route.params.id)])}catch(e){error.value=e.message}}
function edit(){form.value={name:client.value.name,contactInfo:client.value.contactInfo,notes:client.value.notes};editing.value=true}
async function saveClient(){await api('/clients/'+route.params.id,{method:'PUT',body:JSON.stringify(form.value)});editing.value=false;load()}
async function save(){await api('/projects',{method:'POST',body:JSON.stringify({...form.value,clientId:Number(route.params.id)})});modal.value=false;form.value={title:'',description:'',status:'active'};load()}
async function remove(id){if(confirm('Удалить проект и его задачи?')){await api('/projects/'+id,{method:'DELETE'});load()}}
onMounted(load)
</script>
<template><section><button class="back" @click="router.push('/')">← Все клиенты</button><header class="page-head"><div><span class="eyebrow">Клиент</span><h1>{{client.name}}</h1><p>{{client.contactInfo}} · {{client.notes}}</p></div><div class="actions"><button class="ghost" @click="edit">Редактировать</button><button class="primary" @click="modal=true;form={title:'',description:'',status:'active'}">＋ Новый проект</button></div></header><div v-if="error" class="error">{{error}}</div><h2 class="section-title">Проекты <span>{{projects.length}}</span></h2><div class="grid"><article v-for="x in projects" :key="x.id" class="card"><router-link :to="`/projects/${x.id}`"><StatusBadge :status="x.status"/><h3>{{x.title}}</h3><p>{{x.description||'Без описания'}}</p><small>Создан {{new Date(x.createdAt).toLocaleDateString('ru')}}</small></router-link><button class="icon danger" @click="remove(x.id)">×</button></article><button v-if="!projects.length" class="empty" @click="modal=true">＋<b>Создать первый проект</b></button></div><ModalForm v-if="modal" title="Новый проект" @close="modal=false" @submit="save"><label>Название<input v-model="form.title" required></label><label>Описание<textarea v-model="form.description"></textarea></label><label>Статус<select v-model="form.status"><option value="active">Активен</option><option value="paused">Пауза</option><option value="done">Готово</option></select></label></ModalForm><ModalForm v-if="editing" title="Редактировать клиента" @close="editing=false" @submit="saveClient"><label>Название<input v-model="form.name" required></label><label>Контакты<input v-model="form.contactInfo"></label><label>Заметки<textarea v-model="form.notes"></textarea></label></ModalForm></section></template>
