<script setup>
import {onMounted,ref} from 'vue'; import {useRoute,useRouter} from 'vue-router'; import {api} from '../api'; import ModalForm from '../components/ModalForm.vue'; import StatusBadge from '../components/StatusBadge.vue'
const route=useRoute(),router=useRouter(),project=ref({}),tasks=ref([]),modal=ref(false),editing=ref(false),error=ref(''),form=ref({title:'',description:'',status:'active',assignee:'',priority:'normal',dueDate:''})
async function load(){try{[project.value,tasks.value]=await Promise.all([api('/projects/'+route.params.id),api('/tasks?projectId='+route.params.id)])}catch(e){error.value=e.message}}
function edit(){form.value={title:project.value.title,description:project.value.description,status:project.value.status};editing.value=true}
async function saveProject(){await api('/projects/'+route.params.id,{method:'PUT',body:JSON.stringify(form.value)});editing.value=false;load()}
async function save(){await api('/tasks',{method:'POST',body:JSON.stringify({...form.value,projectId:Number(route.params.id)})});modal.value=false;form.value={title:'',description:'',status:'active',assignee:'',priority:'normal',dueDate:''};load()}
async function remove(id){if(confirm('Удалить задачу?')){await api('/tasks/'+id,{method:'DELETE'});load()}}
onMounted(load)
</script>
<template><section><button class="back" @click="router.push('/clients/'+project.clientId)">← К клиенту</button><header class="page-head"><div><span class="eyebrow">Проект</span><div class="title-row"><h1>{{project.title}}</h1><StatusBadge :status="project.status"/></div><p>{{project.description||'Описание не добавлено'}}</p></div><div class="actions"><button class="ghost" @click="edit">Редактировать</button><button class="primary" @click="modal=true;form={title:'',description:'',status:'active',assignee:'',priority:'normal',dueDate:''}">＋ Новая задача</button></div></header><div v-if="error" class="error">{{error}}</div><h2 class="section-title">Задачи <span>{{tasks.length}}</span></h2><div class="task-list"><article v-for="x in tasks" :key="x.id" class="task-row"><router-link :to="`/tasks/${x.id}`"><StatusBadge :status="x.status"/><div><h3>{{x.title}}</h3><p>{{x.description||'Без описания'}} · {{x.assignee||'Не назначена'}} · {{x.dueDate ? new Date(x.dueDate).toLocaleDateString('ru-RU') : 'Без срока'}}</p></div><time>{{new Date(x.createdAt).toLocaleDateString('ru')}}</time><b>→</b></router-link><button class="icon danger" @click="remove(x.id)">×</button></article><button v-if="!tasks.length" class="empty" @click="modal=true">＋<b>Создать первую задачу</b></button></div><ModalForm v-if="modal" title="Новая задача" @close="modal=false" @submit="save"><label>Название<input v-model="form.title" required></label><label>Описание<textarea v-model="form.description"></textarea></label><label>Исполнитель<select v-model="form.assignee"><option value="">Не назначен</option><option value="Lesha">Lesha</option><option value="Denis">Denis</option></select></label><label>Приоритет<select v-model="form.priority"><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="urgent">Срочный</option></select></label><label>Крайний срок<input v-model="form.dueDate" type="date"></label><label>Статус<select v-model="form.status"><option value="active">Активна</option><option value="paused">Пауза</option><option value="done">Готово</option></select></label></ModalForm><ModalForm v-if="editing" title="Редактировать проект" @close="editing=false" @submit="saveProject"><label>Название<input v-model="form.title" required></label><label>Описание<textarea v-model="form.description"></textarea></label><label>Статус<select v-model="form.status"><option value="active">Активен</option><option value="paused">Пауза</option><option value="done">Готово</option></select></label></ModalForm></section></template>
