<script setup>
import {onMounted,onUnmounted,ref} from 'vue'; import {useRoute,useRouter} from 'vue-router'; import {api} from '../api'; import StatusBadge from '../components/StatusBadge.vue'; import ModalForm from '../components/ModalForm.vue'
const route=useRoute(),router=useRouter(),task=ref({}),todos=ref([]),messages=ref([]),todoText=ref(''),message=ref(''),editing=ref(false),error=ref(''),form=ref({}); let timer
async function load(){try{[task.value,todos.value,messages.value]=await Promise.all([api('/tasks/'+route.params.id),api(`/tasks/${route.params.id}/todos`),api(`/tasks/${route.params.id}/messages`)])}catch(e){error.value=e.message}}
async function addTodo(){if(!todoText.value.trim())return;await api(`/tasks/${route.params.id}/todos`,{method:'POST',body:JSON.stringify({text:todoText.value})});todoText.value='';load()}
async function toggle(x){x.checked=!x.checked;await api(`/tasks/${route.params.id}/todos/${x.id}`,{method:'PUT',body:JSON.stringify({checked:x.checked})})}
async function delTodo(id){await api(`/tasks/${route.params.id}/todos/${id}`,{method:'DELETE'});load()}
async function send(){if(!message.value.trim())return;await api(`/tasks/${route.params.id}/messages`,{method:'POST',body:JSON.stringify({text:message.value})});message.value='';load()}
function edit(){form.value={title:task.value.title,description:task.value.description,status:task.value.status};editing.value=true}
async function save(){await api('/tasks/'+route.params.id,{method:'PUT',body:JSON.stringify(form.value)});editing.value=false;load()}
onMounted(()=>{load();timer=setInterval(async()=>{messages.value=await api(`/tasks/${route.params.id}/messages`).catch(()=>messages.value)},5000)});onUnmounted(()=>clearInterval(timer))
</script>
<template><section><button class="back" @click="router.push('/projects/'+task.projectId)">← К проекту</button><header class="page-head compact"><div><span class="eyebrow">Задача #{{task.id}}</span><div class="title-row"><h1>{{task.title}}</h1><StatusBadge :status="task.status"/></div><p>{{task.description||'Описание не добавлено'}}</p></div><button class="ghost" @click="edit">Редактировать</button></header><div v-if="error" class="error">{{error}}</div><div class="task-columns"><div class="panel"><div class="panel-head"><h2>Чек-лист</h2><span>{{todos.filter(x=>x.checked).length}} / {{todos.length}}</span></div><div class="progress"><i :style="{width:(todos.length?todos.filter(x=>x.checked).length/todos.length*100:0)+'%'}"></i></div><div class="todos"><label v-for="x in todos" :key="x.id" :class="{checked:x.checked}"><input type="checkbox" :checked="x.checked" @change="toggle(x)"><span>{{x.text}}</span><button class="icon danger" @click.prevent="delTodo(x.id)">×</button></label></div><form class="inline" @submit.prevent="addTodo"><input v-model="todoText" placeholder="Новый пункт…"><button class="primary">＋</button></form></div><div class="panel chat"><div class="panel-head"><h2>Обсуждение</h2><span class="online">● online</span></div><div class="messages"><div v-if="!messages.length" class="chat-empty">Здесь начнётся обсуждение задачи</div><article v-for="m in messages" :key="m.id" :class="{mine:m.author===localStorage.getItem('crm_user')}"><header><b>{{m.author}}</b><time>{{new Date(m.timestamp+'Z').toLocaleString('ru',{hour:'2-digit',minute:'2-digit',day:'numeric',month:'short'})}}</time></header><p>{{m.text}}</p></article></div><form class="inline" @submit.prevent="send"><input v-model="message" placeholder="Напишите сообщение…"><button class="primary">Отправить</button></form></div></div><ModalForm v-if="editing" title="Редактировать задачу" @close="editing=false" @submit="save"><label>Название<input v-model="form.title" required></label><label>Описание<textarea v-model="form.description"></textarea></label><label>Статус<select v-model="form.status"><option value="active">Активна</option><option value="paused">Пауза</option><option value="done">Готово</option></select></label></ModalForm></section></template>
